---
abstract: 'QBit gettext extractor'
author:
  - 'Sergei Svistunov <sergei-svistunov@yandex.ru>'
build_requires:
  Test::Differences: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.039, CPAN::Meta::Converter version 2.143240'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: qbit_xgettext
requires:
  File::Find: 0
  FindBin: 0
  Getopt::Long: 0
  Pod::Usage: 0
  QBit::Class: 0
  base: 0
  lib: 0
  qbit: 0
  warnings: 0
version: 0.005
